services:
  - type: web
    name: temple-map
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EDIT_PASSWORD
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
